### ISSUE TITLE
Correzioni

### ISSUE THREAD

**Issue by DavideTedesco** [s-e-a-m/seam-lac2020#10]
ho rivisito un po' tutto il testo e lo sto rileggendo. Ri-compliandolo la parte finale delle figure si è spostata... E sarebbe da rimettere apposto. Vedi cosa ne pensi ed in caso se tutto scorre mandiamola in giornata. @grammaton

**Comment by grammaton** [comment]
non ti preoccupare per l'impaginazione… rileggo. Prima di spedirla la faccio leggere ad un paio di madrelingua per un ultimo check.

**Comment by grammaton** [comment]
tutto corretto e impaginato
