### ISSUE TITLE
Biblio 

### ISSUE THREAD

**Issue by DavideTedesco** [s-e-a-m/seam-lac2020#2]
Decidere bibliografia da inserire nel paper oltre all'articolo di Vidolin e Bernardini.

**Comment by grammaton** [comment]
è una buona questione… guardando la biblio dell'articolo stesso, non è che ci sia molto che ci interessi li. Forse potremmo solo citare gli scritti e gli articoli che parlano dei brani che utilizziamo.

**Comment by grammaton** [comment]
@DavideTedesco ho iniziato la bibliografia, ho messo solo un articolo online, manca da mettere Berna, le tre partiture, e credo di avere riferimenti sul fly dal loro paper di presentazione
