### ISSUE TITLE
Conclusions. Appunti

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/seam-lac2020#4]
Il primo concetto da chiarire nelle conclusioni è che la sostenibilità deve puntare al mantenimento dell'idea musicale,  delle peculiarità del brano. Di quella che potremmo definire *process sustainability* partendo proprio dagli esempi di Respighi e Lucier.

**Comment by DavideTedesco** [comment]
E direi inoltre di includere nel _process sustainability_ i tre punti del manifesto, descrivendo anche il fatto che la community possa veramente costruire come un liutaio lo strumento una singola volta che perfezionandolo, e rendendolo accessibile attraverso l'open source, porterebbe ad un'esecuzione ed un'interpretazione delle composizioni che fanno uso dell'elettronica, conservando il pensiero elettronico per una maggior progressione e ricerca all'interno del comporre contemporaneo. (slegando le possibilità di realizzazione dai soli strumenti e mezzi disponibili nell'epoca di realizzazione delle composizioni)
