### ISSUE TITLE
traduzione ita-eng

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/seam-lac2020#5]
@DavideTedesco ho inserito una citazione di nono a riga `368` andrebbe tradotta in inglese nel campo `\footnote` già aperto a fine citazione. Puoi occupartene?

**Comment by DavideTedesco** [comment]
inserita, vedi che ne pensi, ma ve inserita anche quella finale?

**Comment by grammaton** [comment]
no la citazione finale la lascerei così… che ne pensi?

**Comment by grammaton** [comment]
ce n'è un'altra a riga 380 ;).
Non usare gli a capo altrimenti latex non stampa la nota. 

che ne pensi di questi blocchi di citazione? mi sembrano molto pertinenti... che ne pensi?
