### ISSUE TITLE
Primi blocchi corretti

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/seam-lac2020#8]
@DavideTedesco ho corretto fino alla sezione 4.1 SEAM INSTRUMENTS. 
Dai una buona riletta… potrebbe essere una parte archiviabile.

**Comment by DavideTedesco** [comment]
Ho fatto un po' di correzioni et altro fino a 4.1, mi pare che fili tutto. Quale intendi per parte archiviabile?!? @grammaton

**Comment by grammaton** [comment]
inntendevo fino a 4.1, non credo di farci altri interventi, mi concentrerò sul resto.
grazie
