### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/seam-lac2020#9]
@DavideTedesco sto cercando di limare un po il testo di Neatly Layering affinché rimanga in una colonna senza spostare l'impaginazione della sezione successiva. lo so, potrei farne a meno. Ma non je la faccio. dunque rileggendo questo passo

> Who has memories of those disappeared instruments from musical daily doing? And after all, who better than the people that directly worked with Nono can accurately describe and share what happened and what can today happen, unleashing their instrumental and interpretative secrets kept in their minds and nowhere else?

stiamo ufficialmente affemrando che c'è qualcuno che si tiene le cose appizzate… siamo sicuri di volerlo fare? forse una forma di incoraggiamento andrebbe meglio. cioè invece che dirlo con la nostra solita romanissima spocchia, potremmo dire che 

```
There are people have memories of those disappeared instruments from
musical daily doing and, after all, they have directly worked with Nono and
can accurately describe and share what happened and what can today happen. 
```

fammi sapere che ne pensi.

**Comment by DavideTedesco** [comment]
Scusa se non ho no risposto prima, era un'uscita troppo da saccenti quella precedente, e la nuova formula introdotta risulta piú d'incorragiamento come dicevi appunto te.
